apiVersion: apps/v1
kind: Deployment
metadata:
  name: xp-flask-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xp-flask
  template:
    metadata:
      labels:
        app: xp-flask
    spec:
      containers:
      - name: xp-flask
        image: xp-flask:latest
        imagePullPolicy: Never 
        ports:
        - containerPort: 80